name: Build and Deploy Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
        pip install sphinx furo
        pip install -e .
    
    - name: Build documentation
      run: |
        hatch run docs
    
    - name: Prepare GitHub Pages directory
      run: |
        mkdir -p _site
        mkdir -p _site/docs
        # Copy the landing page to the root
        cp index.html _site/
        # Copy the built docs to the docs subdirectory
        cp -r docs/build/* _site/docs/
        # Create a .nojekyll file to ensure GitHub Pages doesn't process the site with Jekyll
        touch _site/.nojekyll
        # Verify the structure
        echo "Site structure:"
        ls -la _site/
        echo "Docs structure:"
        ls -la _site/docs/
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '_site'
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master'
      id: deployment
      uses: actions/deploy-pages@v4 